name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Node.js 16
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: checkout-shadow-root
        uses: actions/checkout@v2
        with:
          ref: 'v2-shadow-root'
      - name: install
        run: npm install --legacy-peer-deps
      - name: build
        working-directory: ./packages/vuetify
        run: npm run build
      - name: publish
        working-directory: ./packages/vuetify
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_SECRET_AUTOMATION}}
        run: npm publish -w 
