name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Node.js 16
        uses: actions/setup-node@v2.4.1
      - name: checkout-shadow-root
        uses: actions/checkout@v2
        with:
          ref: 'v2-shadow-root'
      - name: install
        run: npm install --force
        working-directory: ./packages/vuetify
      - name: build
        run: npm run build
        working-directory: ./packages/vuetify
      - name: npm publish
        run: npm run publish
